import {
  Card,
  Image,
  Stack,
  CardBody,
  Heading,
  Text,
  CardFooter,
  Button,
  ButtonGroup,
  Link,
} from "@chakra-ui/react";
import { FaGithub } from "react-icons/fa";
import { ViewIcon } from "@chakra-ui/icons";

export interface publication {
  Title: string;
  Descrition: string;
  Year: string;
}

const Publication = () => {
  return (
    <Card
      direction={{ base: "column", sm: "row" }}
      overflow="hidden"
      variant="outline"
    >
      <Image
        objectFit="cover"
        maxW={{ base: "100%", sm: "200px" }}
        src="./publication_cover.jpg"
        alt="Discriminator-Free Generative Adversarial Attack"
      />

      <Stack>
        <CardBody>
          <Heading size="md">
            Discriminator-Free Generative Adversarial Attack
          </Heading>

          <Text py="2">
            In this work, we find that the discriminator could be not necessary
            for generative-based adversarial attack, and propose the{" "}
            <Text as="b">Symmetric Saliency-based Auto-Encoder (SSAE)</Text> to
            generate the perturbations, which is composed of the saliency map
            module and the angle-norm disentanglement of the features module.
            The advantage of our proposed method lies in that it is not
            depending on discriminator, and uses the generative saliency map to
            pay more attention to label-relevant regions. The extensive
            experiments among the various tasks, datasets, and models
            demonstrate that the adversarial examples generated by SSAE not only
            make the widely-used models collapse, but also achieves good visual
            quality.
          </Text>
        </CardBody>
        <CardFooter>
          <ButtonGroup spacing="2">
            <Button leftIcon={<ViewIcon />} colorScheme="teal" variant="outline">
              <Link href="https://arxiv.org/pdf/2107.09225.pdf" target="_blank">
                Paper
              </Link>
            </Button>
            <Button leftIcon={<FaGithub />} colorScheme="teal" variant="solid">
              <Link href="https://github.com/BravoLu/SSAE" target="_blank">
                Source Code
              </Link>
            </Button>
          </ButtonGroup>
        </CardFooter>
      </Stack>
    </Card>
  );
};

export default Publication;
